nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
  cpu:
    - "current"
    - "x64"
    - "arm64"
  libc:
    - "current"
    - "glibc"
    - "musl"
