name: Pull Request
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  preview:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az account list --query "[].{Name:name, IsDefault:isDefault}"
          az aks get-credentials --resource-group IvoryRG --name ivory_aks --file $GITHUB_WORKSPACE/infrastructure/kubeconfig
          chmod 444 $GITHUB_WORKSPACE/infrastructure/kubeconfig
      # - name: Get Kubenetes config from Azure
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: 2.0.72
      #     inlineScript: |
      #       az account list --query "[].{Name:name, IsDefault:isDefault}"
      #       az aks get-credentials --resource-group IvoryRG --name ivory_aks --file $GITHUB_WORKSPACE/infrastructure/kubeconfig
      #       chmod 444 $GITHUB_WORKSPACE/infrastructure/kubeconfig
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ github.head_ref }}
          work-dir: ./infrastructure
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          KUBECONFIG: ./kubeconfig
          BRANCH_NAME: ${{ github.head_ref }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}